services: 
    sql-server-db:
        container_name: puppies-sql-server-db
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Password123!"
            ACCEPT_EULA: "Y"
    redis:
        image: "redis:alpine"
        command: redis-server --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        ports:
        - "6379:6379"